### PR TITLE
Runtime 23.08

### PR DESCRIPTION
**Pull request by bbhtt**
Might require more patches but I can't locally build... each small addon failing makes the entire openframeworks build fail and it is pretty annoying...

### CODE REVIEW

**Comment by bbhtt** [comment]
Will deal later:

```
/run/build/openframeworks/addons/ofxPDSP/src/messages/ExtSequencer.cpp:11:10: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
   11 |     for (size_t i = 0; i < instances.size(); ++i) {
      |          ^~~~~~
      |          std::size_t
In file included from /usr/include/c++/13.2.0/bits/requires_hosted.h:31,
                 from /usr/include/c++/13.2.0/vector:60,
                 from /run/build/openframeworks/addons/ofxPDSP/src/messages/ExtSequencer.h:9,
                 from /run/build/openframeworks/addons/ofxPDSP/src/messages/ExtSequencer.cpp:2:
/usr/include/c++/13.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:308:33: note: ‘std::size_t’ declared here
  308 |   typedef __SIZE_TYPE__         size_t;
      |                                 ^~~~~~
/run/build/openframeworks/addons/ofxPDSP/src/messages/ExtSequencer.cpp:11:24: error: ‘i’ was not declared in this scope
   11 |     for (size_t i = 0; i < instances.size(); ++i) {
      |                        ^
```

**Comment by bbhtt** [comment]
```
In file included from /app/include/dispatch/dispatch.h:32,
                 from /run/build/openframeworks/addons/ofxHapPlayer/src/ofxHapPlayer.cpp:48:
/app/include/os/generic_unix_base.h:58:18: error: missing binary operator before token "("
   58 | #if __has_feature(assume_nonnull)
      |                  ^
/app/include/os/generic_unix_base.h:72:18: error: missing binary operator before token "("
   72 | #if __has_feature(attribute_availability_swift)
      |                  ^
/app/include/os/generic_unix_base.h:97:18: error: missing binary operator before token "("
   97 | #if __has_feature(objc_fixed_enum) || __has_extension(cxx_strong_enums)
      |                  ^
```

**Comment by bbhtt** [comment]
Looks like ofchapplayer is incompatible with GCC https://github.com/bangnoise/ofxHapPlayer/issues/66

**Comment by bbhtt** [comment]
```
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp: In constructor ‘ofxHap::AudioDecoder::AudioDecoder(const ofxHap::AudioParameters&, int&)’:
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:47:18: error: ‘avcodec_alloc_context3’ was not declared in this scope; did you mean ‘avio_alloc_context’?
   47 |     _codec_ctx = avcodec_alloc_context3(nullptr);
      |                  ^~~~~~~~~~~~~~~~~~~~~~
      |                  avio_alloc_context
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:69:18: error: ‘avcodec_parameters_to_context’ was not declared in this scope; did you mean ‘avcodec_parameters_copy’?
   69 |         result = avcodec_parameters_to_context(_codec_ctx, params.parameters);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  avcodec_parameters_copy
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:79:22: error: ‘avcodec_open2’ was not declared in this scope; did you mean ‘avio_open2’?
   79 |             result = avcodec_open2(_codec_ctx, decoder, &opts);
      |                      ^~~~~~~~~~~~~
      |                      avio_open2
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp: In destructor ‘ofxHap::AudioDecoder::~AudioDecoder()’:
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:90:9: error: ‘avcodec_free_context’ was not declared in this scope; did you mean ‘avformat_free_context’?
   90 |         avcodec_free_context(&_codec_ctx);
      |         ^~~~~~~~~~~~~~~~~~~~
      |         avformat_free_context
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp: In member function ‘int ofxHap::AudioDecoder::send(AVPacket*)’:
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:152:12: error: ‘avcodec_send_packet’ was not declared in this scope; did you mean ‘avcodec_get_name’?
  152 |     return avcodec_send_packet(_codec_ctx, packet);
      |            ^~~~~~~~~~~~~~~~~~~
      |            avcodec_get_name
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp: In member function ‘int ofxHap::AudioDecoder::receive(AVFrame*)’:
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:168:12: error: ‘avcodec_receive_frame’ was not declared in this scope; did you mean ‘avcodec_profile_name’?
  168 |     return avcodec_receive_frame(_codec_ctx, frame);
      |            ^~~~~~~~~~~~~~~~~~~~~
      |            avcodec_profile_name
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp: In member function ‘void ofxHap::AudioDecoder::flush()’:
/run/build/openframeworks/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:205:5: error: ‘avcodec_flush_buffers’ was not declared in this scope
  205 |     avcodec_flush_buffers(_codec_ctx);
      |     ^~~~~~~~~~~~~~~~~~~~~
make[1]: *** [/run/build/openframeworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:360: /run/build/openframeworks/addons/obj/linux64/Release/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.o] Error 1
make[1]: Leaving directory '/run/build/openframeworks/apps/d3cod3/Mosaic'
```

**Comment by d3cod3** [comment]
Hey, thank you so much for your help fixing compilation for OF 0.11.2!!!

I was just updating stuff for the last Mosaic release 0.6.6, so i just added most of your fixings to a pull request running just now. I've removed various addons and cleaned the code, so less difficulties for now.

Let's see if the pull compile...

**Comment by bbhtt** [comment]
Closing in favour of https://github.com/flathub/org.d3cod3.Mosaic/pull/3

**Pull request closed without merging**
