### PR TITLE
fixing compat with OF 0.12

### PR DESCRIPTION
**Pull request by d3cod3**

### CODE REVIEW

**Comment by hfiguiere** [comment]
the proper fix is to NOT link libstdc++fs.

it should never have been specified in the first place it has been part of the C++17 support for long enough and only existed for partial support.
The reason this fail here is that the `.a` shims are not provided in the runtime. (it's not even new)

It's a case of "it builds on Ubuntu".

**Comment by d3cod3** [comment]
> the proper fix is to NOT link libstdc++fs.
> 
> it should never have been specified in the first place it has been part of the C++17 support for long enough and only existed for partial support. The reason this fail here is that the `.a` shims are not provided in the runtime. (it's not even new)
> 
> It's a case of "it builds on Ubuntu".

Thnak you for the info!
I just have to see how to do it, because the origin of the problem from openframeworks 0.12, that come pre-packed with all his internal configs, and libstdc++fs is linked from there.

**Comment by hfiguiere** [comment]
the easiest usually is to patch.

**Comment by d3cod3** [comment]
> the easiest usually is to patch.

I just found this in a makefile config file:

```
ifeq ($(OF_USING_STD_FS),1)
	# gcc 8 need special file system linking with -lstdc++fs. gcc 9 onwards doesn't
	ifeq ("$(GCC_MAJOR)","8")
		PLATFORM_LDFLAGS += -lstdc++fs
	endif
endif
```

I will patch it as you suggest

**Pull request merged**
